# Generated by Django 4.0.3 on 2022-03-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_new_delete_webscraper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
